version: "3.9"
services:
  evolution-api:
    image: atendai/evolution-api:v2.1.1
    restart: always
    ports:
      - "8080:8080"
    environment:
      - AUTHENTICATION_API_KEY=super_chave_123
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://pguser:pgpass@db:5432/evolutiondb
      - CONFIG_SESSION_PHONE_VERSION=2.3000.1024363850
      
    volumes: 
      - evolution_instances:/evolution/instances
    depends_on:
      - db
  
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: evolutiondb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  evolution_instances:
  pgdata: